import { DepartmentConfig, Grievance, ProcurementProject, TransparencyScore } from "@/types/grievance";

export const CATEGORY_CONFIGS: DepartmentConfig[] = [
  {
    category: "Sanitation & Waste",
    department: "Municipal Corporation",
    defaultSlaDays: 2,
    isVisualARCategory: true,
    autoRouteCode: "MC-SAN",
    escalationChain: {
      ward: "Sanitation Inspector (Ward)",
      zonal: "Zonal Health Officer",
      district: "Municipal Commissioner",
      state: "Principal Secretary (Urban Development)",
    },
    subcategories: [
      "Garbage Dump / Overflowing Bin",
      "Blocked Open Drain / Sewer",
      "Dead Animal Carcass Removal",
      "Public Urinal / Toilet Maintenance",
      "Plastic Burning / Illegal Littering",
    ],
  },
  {
    category: "Roads & Infrastructure",
    department: "Public Works Department",
    defaultSlaDays: 4,
    isVisualARCategory: true,
    autoRouteCode: "PWD-RDS",
    escalationChain: {
      ward: "Junior Engineer (Ward)",
      zonal: "Assistant Executive Engineer",
      district: "Superintending Engineer (PWD)",
      state: "State Highway Ombudsman",
    },
    subcategories: [
      "Pothole / Road Surface Crater",
      "Broken Footpath / Paver Blocks",
      "Open / Damaged Manhole",
      "Malfunctioning Streetlight",
      "Missing Traffic Sign / Guardrail",
    ],
  },
  {
    category: "Water & Electricity",
    department: "Water Board / Electricity Board",
    defaultSlaDays: 1,
    isVisualARCategory: true,
    autoRouteCode: "WEB-UTL",
    escalationChain: {
      ward: "Lineman / Water Works Inspector",
      zonal: "Sub-Divisional Officer",
      district: "Chief Engineer (Utilities)",
      state: "Electricity & Water Regulatory Commission",
    },
    subcategories: [
      "Main Pipeline Burst / Massive Leak",
      "Contaminated / Turbid Tap Water",
      "Overhead Wire Hanging / Transformer Spark",
      "Frequent Unscheduled Power Cuts",
      "Low Voltage / Faulty Electric Meter",
    ],
  },
  {
    category: "Health Services",
    department: "Health Department",
    defaultSlaDays: 3,
    isVisualARCategory: false,
    autoRouteCode: "HLT-DEP",
    escalationChain: {
      ward: "Primary Health Centre In-charge",
      zonal: "Block Medical Officer",
      district: "Chief Medical Officer (CMO)",
      state: "Director General Health Services",
    },
    subcategories: [
      "Shortage of Essential Medicines in PHC",
      "Doctor / Staff Absenteeism in Govt Hospital",
      "Ambulance Delay / Denial of Emergency Care",
      "Dengue / Malaria Mosquito Breeding Site",
      "Substandard Hospital Sanitation",
    ],
  },
  {
    category: "Education",
    department: "Education Department",
    defaultSlaDays: 5,
    isVisualARCategory: false,
    autoRouteCode: "EDU-DEP",
    escalationChain: {
      ward: "Cluster Resource Centre Coordinator",
      zonal: "Block Education Officer",
      district: "District Inspector of Schools",
      state: "Principal Secretary (School Education)",
    },
    subcategories: [
      "Dilapidated School Building / Ceiling Leak",
      "Teacher Absenteeism / Low Quality Teaching",
      "Mid-Day Meal Substandard / Contaminated",
      "Lack of Functional Girls' Toilet / Water",
      "Private School Capitation Fee Demands",
    ],
  },
  {
    category: "Law & Order / Safety",
    department: "Police / Traffic Department",
    defaultSlaDays: 1,
    isVisualARCategory: false,
    autoRouteCode: "POL-SEC",
    escalationChain: {
      ward: "Beat Officer / Sub-Inspector",
      zonal: "Assistant Commissioner of Police (ACP)",
      district: "Superintendent of Police (DCP/SP)",
      state: "Director General of Police / Home Dept",
    },
    subcategories: [
      "Reckless Driving / Heavy Traffic Choke",
      "Illegal Parking Blocking Emergency Access",
      "Public Harassment / Dark Unlit Stretches",
      "Excessive Night Noise / Loudspeakers",
      "Unauthorized Liquor / Gambling Vending",
    ],
  },
  {
    category: "Land, Revenue & Certificates",
    department: "Revenue Department",
    defaultSlaDays: 7,
    isVisualARCategory: false,
    autoRouteCode: "REV-LND",
    escalationChain: {
      ward: "Village Administrative Officer (Patwari)",
      zonal: "Tahsildar / Naib Tahsildar",
      district: "District Collector / Magistrate",
      state: "Board of Revenue / Revenue Tribunal",
    },
    subcategories: [
      "Delay in Caste / Income / Domicile Certificate",
      "Land Record Mutation / Jamabandi Discrepancy",
      "Encroachment on Common Gram Sabha / Govt Land",
      "Delay in Land Demarcation Survey",
      "Stamp Duty / Sub-Registrar Harassment",
    ],
  },
  {
    category: "Welfare & Social Security",
    department: "Social Welfare Department",
    defaultSlaDays: 7,
    isVisualARCategory: false,
    autoRouteCode: "SOC-WEL",
    escalationChain: {
      ward: "Welfare Extension Officer",
      zonal: "Child Development Project Officer",
      district: "District Social Welfare Officer",
      state: "Social Justice Secretary",
    },
    subcategories: [
      "Old Age / Widow Pension Delay (2+ Months)",
      "PDS Ration Dealer Black Marketing / Underweighing",
      "Disability Prosthetics / Allowance Pending",
      "Scholarship Disbursal Delay for SC/ST/OBC",
      "Anganwadi Nutrition Ration Non-Distribution",
    ],
  },
  {
    category: "Environment & Disaster",
    department: "Pollution Control Board / Disaster Management",
    defaultSlaDays: 2,
    isVisualARCategory: true,
    autoRouteCode: "ENV-DIS",
    escalationChain: {
      ward: "Environmental Junior Scientific Officer",
      zonal: "Regional Officer (PCB)",
      district: "District Disaster Management Authority",
      state: "National Green Tribunal / State Env Board",
    },
    subcategories: [
      "Toxic Industrial Effluent into Waterbody",
      "Thick Chemical Smoke / Stubble Burning",
      "Severe Waterlogging / Flash Flood Inundation",
      "Illegal Tree Cutting in Protected Green Belt",
      "Hazardous E-Waste / Biomedical Waste Dumping",
    ],
  },
  {
    category: "Corruption & Accountability",
    department: "Anti-Corruption Bureau",
    defaultSlaDays: 14,
    isVisualARCategory: false,
    autoRouteCode: "ACB-VIG",
    escalationChain: {
      ward: "Inspector of Police (ACB Vigilance)",
      zonal: "Deputy SP (ACB Division)",
      district: "Superintendent of Police (ACB Range)",
      state: "State Vigilance Commissioner / Lokayukta",
    },
    subcategories: [
      "Bribe Demanded for Service Delivery / Certificate",
      "Kickbacks in Public Works Tenders",
      "Ghost Beneficiaries in DBT Schemes",
      "Disproportionate Assets of Public Servant",
      "Misuse of Official Government Vehicles / Resources",
    ],
  },
];

export const SEED_PROCUREMENT_PROJECTS: ProcurementProject[] = [
  {
    _id: "proc-101",
    projectId: "PWD-2025-BLR-042",
    title: "Outer Ring Road Bituminous Resurfacing & Storm Drain Rebuild",
    department: "Public Works Department",
    contractorName: "Apex InfraTech Projects Ltd.",
    sanctionedBudgetInLakhs: 485.5,
    spendToDateInLakhs: 320.8,
    status: "active",
    location: {
      lat: 12.9716,
      lng: 77.5946,
      address: "Outer Ring Road, Junction 4, Ward 12",
      radiusMeters: 450,
    },
    startDate: "2025-06-15",
    expectedCompletionDate: "2026-03-31",
    workOrderNumber: "WO/PWD/2025/8841-A",
  },
  {
    _id: "proc-102",
    projectId: "WEB-2025-PIP-019",
    title: "Drinking Water Feeder Pipeline 600mm Replacement",
    department: "Water Board / Electricity Board",
    contractorName: "JalShakti Hydro Systems Pvt. Ltd.",
    sanctionedBudgetInLakhs: 215.0,
    spendToDateInLakhs: 198.4,
    status: "active",
    location: {
      lat: 12.9812,
      lng: 77.6045,
      address: "14th Cross, Malleshwaram West, Ward 8",
      radiusMeters: 300,
    },
    startDate: "2025-08-01",
    expectedCompletionDate: "2026-02-28",
    workOrderNumber: "WO/BWSSB/2025/1109",
  },
  {
    _id: "proc-103",
    projectId: "MC-2025-SWM-088",
    title: "Decentralized Wet Waste Processing & Bio-Methanization Plant",
    department: "Municipal Corporation",
    contractorName: "GreenTerra Environmental Engineers",
    sanctionedBudgetInLakhs: 360.0,
    spendToDateInLakhs: 275.0,
    status: "active",
    location: {
      lat: 12.9352,
      lng: 77.6245,
      address: "Koramangala 6th Block Civic Amenity Site",
      radiusMeters: 500,
    },
    startDate: "2025-04-10",
    expectedCompletionDate: "2026-01-30",
    workOrderNumber: "WO/BBMP/SWM/7762",
  },
];

export const SEED_GRIEVANCES: Grievance[] = [
  // 1. Visual Resolved Grievance (for AR Ghost Preview)
  {
    _id: "grv-001",
    citizenId: "cit-101",
    citizenName: "Aarav Sharma",
    citizenPhone: "+91 98450 12345",
    category: "Roads & Infrastructure",
    subcategory: "Pothole / Road Surface Crater",
    department: "Public Works Department",
    description:
      "Massive 1.5-meter deep pothole right at the intersection causing multiple two-wheeler accidents during monsoon.",
    isAnonymous: false,
    location: {
      lat: 12.9716,
      lng: 77.5946,
      headingDegrees: 142,
      pitch: -12,
      roll: 2,
      accuracyMeters: 3.5,
      address: "MG Road Junction, Ward 12, Central Zone",
    },
    capturePhotoUrl:
      "https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&w=800&q=80",
    resolvedPhotoUrl:
      "https://images.unsplash.com/photo-1541888946425-d0fbb186156f?auto=format&fit=crop&w=800&q=80",
    status: "resolved",
    slaDays: 4,
    slaDeadline: new Date(Date.now() - 36 * 3600 * 1000).toISOString(),
    escalationLevel: "ward",
    assignedWorkerId: "wrk-201",
    assignedWorkerName: "Ramesh Kumar (Junior Engineer)",
    officialNotes:
      "Cold-mix asphalt patch filled and roller-compacted to grade. Quality test verified on-site.",
    procurementProjectId: "proc-101",
    priority: "high",
    wardNumber: "Ward 12",
    zoneName: "Central Zone",
    createdAt: new Date(Date.now() - 5 * 86400 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 86400 * 1000).toISOString(),
    resolvedAt: new Date(Date.now() - 1 * 86400 * 1000).toISOString(),
    civicPointsAwarded: 25,
  },

  // 2. Sanitation In-Progress (Visual category)
  {
    _id: "grv-002",
    citizenId: "cit-102",
    citizenName: "Priya Sundaram",
    category: "Sanitation & Waste",
    subcategory: "Garbage Dump / Overflowing Bin",
    department: "Municipal Corporation",
    description:
      "Community secondary garbage container hasn't been cleared for 4 days. Waste spilled over 30 meters attracting stray animals.",
    isAnonymous: false,
    location: {
      lat: 12.9765,
      lng: 77.5998,
      headingDegrees: 285,
      pitch: -8,
      roll: 0,
      accuracyMeters: 4.1,
      address: "Near Govt Girls High School, Ward 12",
    },
    capturePhotoUrl:
      "https://images.unsplash.com/photo-1605600659873-d808a13e4d2a?auto=format&fit=crop&w=800&q=80",
    status: "in_progress",
    slaDays: 2,
    slaDeadline: new Date(Date.now() + 18 * 3600 * 1000).toISOString(), // 18 hrs left
    escalationLevel: "ward",
    assignedWorkerId: "wrk-202",
    assignedWorkerName: "Mahesh Babu (Sanitation Lead)",
    officialNotes: "Sanitation truck BBMP-KA-04-E-4421 dispatched for mechanical lifting.",
    priority: "urgent",
    wardNumber: "Ward 12",
    zoneName: "Central Zone",
    createdAt: new Date(Date.now() - 30 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    civicPointsAwarded: 15,
  },

  // 3. Water & Electricity - Escalated to Zonal (SLA Breached)
  {
    _id: "grv-003",
    citizenId: "cit-103",
    citizenName: "Vikram Malhotra",
    category: "Water & Electricity",
    subcategory: "Main Pipeline Burst / Massive Leak",
    department: "Water Board / Electricity Board",
    description:
      "High-pressure underground drinking water pipe burst. Millions of liters flooding residential lane, water pressure zero in 40 houses.",
    isAnonymous: false,
    location: {
      lat: 12.9812,
      lng: 77.6045,
      headingDegrees: 45,
      pitch: -15,
      roll: 1,
      accuracyMeters: 2.8,
      address: "14th Cross, Malleshwaram West, Ward 8",
    },
    capturePhotoUrl:
      "https://images.unsplash.com/photo-1584467735815-f778f274e296?auto=format&fit=crop&w=800&q=80",
    status: "escalated",
    slaDays: 1,
    slaDeadline: new Date(Date.now() - 14 * 3600 * 1000).toISOString(), // Breached 14 hrs ago!
    escalationLevel: "zonal",
    escalationHistory: [
      {
        fromLevel: "ward",
        toLevel: "zonal",
        escalatedAt: new Date(Date.now() - 14 * 3600 * 1000).toISOString(),
        reason: "SLA legal window (24h) expired without resolution by Ward Lineman. Auto-escalated to Sub-Divisional Officer.",
        triggeredBy: "cron_sla_breach",
      },
    ],
    procurementProjectId: "proc-102",
    priority: "urgent",
    wardNumber: "Ward 8",
    zoneName: "West Zone",
    createdAt: new Date(Date.now() - 38 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 14 * 3600 * 1000).toISOString(),
    civicPointsAwarded: 20,
  },

  // 4. Health Services - Acknowledged
  {
    _id: "grv-004",
    citizenId: "cit-104",
    citizenName: "Sunita Deshmukh",
    category: "Health Services",
    subcategory: "Shortage of Essential Medicines in PHC",
    department: "Health Department",
    description:
      "Primary Health Centre has had no anti-rabies vaccines or paracetamol syrups for infants since last Monday. Patients being turned away.",
    isAnonymous: false,
    location: {
      lat: 12.9641,
      lng: 77.5855,
      headingDegrees: 0,
      address: "Chamarajpet Community Health Centre, Ward 24",
    },
    status: "acknowledged",
    slaDays: 3,
    slaDeadline: new Date(Date.now() + 42 * 3600 * 1000).toISOString(),
    escalationLevel: "ward",
    assignedWorkerName: "Dr. K. Swaminathan (PHC Medical Officer)",
    priority: "high",
    wardNumber: "Ward 24",
    zoneName: "South Zone",
    createdAt: new Date(Date.now() - 30 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 12 * 3600 * 1000).toISOString(),
    civicPointsAwarded: 20,
  },

  // 5. Education - Escalated to District Collector (SLA Breached multiple times)
  {
    _id: "grv-005",
    citizenId: "cit-105",
    citizenName: "Mohammad Farooq",
    category: "Education",
    subcategory: "Dilapidated School Building / Ceiling Leak",
    department: "Education Department",
    description:
      "Rainwater leaking through classroom ceiling onto electrical wiring in Class 4-5 room. Severe hazard for 65 children.",
    isAnonymous: false,
    location: {
      lat: 12.9555,
      lng: 77.5712,
      headingDegrees: 180,
      address: "Govt Urdu Model Primary School, Basavanagudi, Ward 19",
    },
    status: "escalated",
    slaDays: 5,
    slaDeadline: new Date(Date.now() - 48 * 3600 * 1000).toISOString(),
    escalationLevel: "district",
    escalationHistory: [
      {
        fromLevel: "ward",
        toLevel: "zonal",
        escalatedAt: new Date(Date.now() - 72 * 3600 * 1000).toISOString(),
        reason: "Ward CRCC failed to act within 5 days.",
        triggeredBy: "cron_sla_breach",
      },
      {
        fromLevel: "zonal",
        toLevel: "district",
        escalatedAt: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
        reason: "Block Education Officer unresponsive for 48 hours post-escalation. Escalated to District Collector.",
        triggeredBy: "cron_sla_breach",
      },
    ],
    priority: "urgent",
    wardNumber: "Ward 19",
    zoneName: "South Zone",
    createdAt: new Date(Date.now() - 8 * 86400 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
    civicPointsAwarded: 30,
  },

  // 6. Law & Order - Submitted (Fresh)
  {
    _id: "grv-006",
    citizenId: "cit-106",
    citizenName: "Divya Nair",
    category: "Law & Order / Safety",
    subcategory: "Public Harassment / Dark Unlit Stretches",
    department: "Police / Traffic Department",
    description:
      "Dark stretch between Metro Pillar 140 and bus stop has 6 non-functional streetlights and frequent eve-teasing in the evenings after 8 PM.",
    isAnonymous: false,
    location: {
      lat: 12.9892,
      lng: 77.5911,
      headingDegrees: 90,
      address: "Near Seshadripuram Metro Station, Ward 15",
    },
    status: "submitted",
    slaDays: 1,
    slaDeadline: new Date(Date.now() + 16 * 3600 * 1000).toISOString(),
    escalationLevel: "ward",
    priority: "high",
    wardNumber: "Ward 15",
    zoneName: "North Zone",
    createdAt: new Date(Date.now() - 8 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 8 * 3600 * 1000).toISOString(),
    civicPointsAwarded: 15,
  },

  // 7. Land & Revenue - In Progress
  {
    _id: "grv-007",
    citizenId: "cit-107",
    citizenName: "Ranganathan K.",
    category: "Land, Revenue & Certificates",
    subcategory: "Delay in Caste / Income / Domicile Certificate",
    department: "Revenue Department",
    description:
      "Income certificate application No. INC/2025/88129 pending for 28 days without query or rejection. Required urgently for college admission.",
    isAnonymous: false,
    location: {
      lat: 12.9221,
      lng: 77.6189,
      headingDegrees: 0,
      address: "Tahsildar Office, BTM Layout 2nd Stage, Ward 31",
    },
    status: "in_progress",
    slaDays: 7,
    slaDeadline: new Date(Date.now() + 72 * 3600 * 1000).toISOString(),
    escalationLevel: "ward",
    assignedWorkerName: "S. N. Murthy (Revenue Inspector)",
    priority: "medium",
    wardNumber: "Ward 31",
    zoneName: "South Zone",
    createdAt: new Date(Date.now() - 4 * 86400 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 86400 * 1000).toISOString(),
    civicPointsAwarded: 15,
  },

  // 8. Welfare - Escalated to State Ombudsman
  {
    _id: "grv-008",
    citizenId: "cit-108",
    citizenName: "Gangamma (Senior Citizen)",
    category: "Welfare & Social Security",
    subcategory: "Old Age / Widow Pension Delay (2+ Months)",
    department: "Social Welfare Department",
    description:
      "Widow pension for 72-year-old stopped for 4 consecutive months despite biometric re-verification completed in October at bank branch.",
    isAnonymous: false,
    location: {
      lat: 12.9412,
      lng: 77.5623,
      headingDegrees: 0,
      address: "Gandhi Bazaar Slum Board Colony, Ward 22",
    },
    status: "escalated",
    slaDays: 7,
    slaDeadline: new Date(Date.now() - 120 * 3600 * 1000).toISOString(),
    escalationLevel: "state",
    escalationHistory: [
      {
        fromLevel: "ward",
        toLevel: "zonal",
        escalatedAt: new Date(Date.now() - 120 * 3600 * 1000).toISOString(),
        reason: "Welfare officer failed to disburse within 7 days SLA.",
        triggeredBy: "cron_sla_breach",
      },
      {
        fromLevel: "zonal",
        toLevel: "district",
        escalatedAt: new Date(Date.now() - 72 * 3600 * 1000).toISOString(),
        reason: "Zonal CDPO inactive.",
        triggeredBy: "cron_sla_breach",
      },
      {
        fromLevel: "district",
        toLevel: "state",
        escalatedAt: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
        reason: "District Magistrate breach timeout reached. Handed to State Grievance Ombudsman for statutory inquiry.",
        triggeredBy: "cron_sla_breach",
      },
    ],
    priority: "urgent",
    wardNumber: "Ward 22",
    zoneName: "South Zone",
    createdAt: new Date(Date.now() - 15 * 86400 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
    civicPointsAwarded: 40,
  },

  // 9. Environment & Disaster - In Progress (Visual)
  {
    _id: "grv-009",
    citizenId: "cit-109",
    citizenName: "Tanmay Ghosh",
    category: "Environment & Disaster",
    subcategory: "Toxic Industrial Effluent into Waterbody",
    department: "Pollution Control Board / Disaster Management",
    description:
      "Chemical tanker releasing foaming reddish wastewater into stormwater canal entering Bellandur lake basin.",
    isAnonymous: false,
    location: {
      lat: 12.9352,
      lng: 77.6698,
      headingDegrees: 210,
      pitch: -5,
      roll: -1,
      accuracyMeters: 5.0,
      address: "Kariyammana Agrahara Lake Feeder Canal, Ward 44",
    },
    capturePhotoUrl:
      "https://images.unsplash.com/photo-1611273426858-450d8e3c9fce?auto=format&fit=crop&w=800&q=80",
    status: "in_progress",
    slaDays: 2,
    slaDeadline: new Date(Date.now() + 12 * 3600 * 1000).toISOString(),
    escalationLevel: "ward",
    assignedWorkerName: "Dr. B. K. Rao (PCB Scientific Officer)",
    priority: "urgent",
    wardNumber: "Ward 44",
    zoneName: "East Zone",
    createdAt: new Date(Date.now() - 36 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
    civicPointsAwarded: 35,
  },

  // 10. Corruption & Accountability - Isolated Anonymous Whistleblowing
  {
    _id: "grv-010",
    citizenId: "anon-whistleblower-7749",
    citizenName: "Anonymous Citizen (Identity Encrypted)",
    category: "Corruption & Accountability",
    subcategory: "Bribe Demanded for Service Delivery / Certificate",
    department: "Anti-Corruption Bureau",
    description:
      "Revenue sub-registrar clerk demanded ₹15,000 cash bribe for issuing certified land deed copy; audio recording and token slips attached. Direct harassment of senior citizen.",
    isAnonymous: true,
    location: {
      lat: 12.9788,
      lng: 77.5812,
      headingDegrees: 0,
      address: "Sub-Registrar Office, Gandhinagar, Ward 11",
    },
    capturePhotoUrl:
      "https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&w=800&q=80",
    status: "in_progress",
    slaDays: 14,
    slaDeadline: new Date(Date.now() + 7 * 86400 * 1000).toISOString(),
    escalationLevel: "ward",
    assignedWorkerName: "Inspector R. D. Patil (ACB Vigilance Wing)",
    officialNotes: "Preliminary verification report initiated under Section 7 of PC Act. Surveillance camera logs preserved.",
    priority: "urgent",
    wardNumber: "Ward 11",
    zoneName: "Central Zone",
    createdAt: new Date(Date.now() - 4 * 86400 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 86400 * 1000).toISOString(),
    civicPointsAwarded: 50,
  },

  // 11. Additional visual resolved item for Ghost preview
  {
    _id: "grv-011",
    citizenId: "cit-101",
    citizenName: "Aarav Sharma",
    category: "Sanitation & Waste",
    subcategory: "Garbage Dump / Overflowing Bin",
    department: "Municipal Corporation",
    description:
      "Huge open garbage pile blocking sidewalk opposite community center. Stench unbearable for residents.",
    isAnonymous: false,
    location: {
      lat: 12.9698,
      lng: 77.5921,
      headingDegrees: 310,
      pitch: -10,
      roll: 1,
      accuracyMeters: 3.2,
      address: "8th Main Road, Ward 12, Central Zone",
    },
    capturePhotoUrl:
      "https://images.unsplash.com/photo-1530587191325-3db32d826c18?auto=format&fit=crop&w=800&q=80",
    resolvedPhotoUrl:
      "https://images.unsplash.com/photo-1577495508048-b635879837f1?auto=format&fit=crop&w=800&q=80",
    status: "resolved",
    slaDays: 2,
    slaDeadline: new Date(Date.now() - 48 * 3600 * 1000).toISOString(),
    escalationLevel: "ward",
    assignedWorkerId: "wrk-202",
    assignedWorkerName: "Mahesh Babu (Sanitation Lead)",
    officialNotes:
      "Debris cleared completely, lime powder disinfected, new twin dustbins installed on-site.",
    priority: "high",
    wardNumber: "Ward 12",
    zoneName: "Central Zone",
    createdAt: new Date(Date.now() - 4 * 86400 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 86400 * 1000).toISOString(),
    resolvedAt: new Date(Date.now() - 2 * 86400 * 1000).toISOString(),
    civicPointsAwarded: 15,
  },

  // 12. Additional Road Pothole in Progress for Field Worker Demo
  {
    _id: "grv-012",
    citizenId: "cit-110",
    citizenName: "Kavita Reddy",
    category: "Roads & Infrastructure",
    subcategory: "Pothole / Road Surface Crater",
    department: "Public Works Department",
    description:
      "Twin deep craters on flyover approach causing severe tire punctures. Needs urgent cold-mix asphalt filling.",
    isAnonymous: false,
    location: {
      lat: 12.9734,
      lng: 77.5978,
      headingDegrees: 165,
      pitch: -14,
      roll: 0,
      accuracyMeters: 2.9,
      address: "Richmond Circle Flyover Approach, Ward 12",
    },
    capturePhotoUrl:
      "https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&w=800&q=80",
    status: "in_progress",
    slaDays: 4,
    slaDeadline: new Date(Date.now() + 32 * 3600 * 1000).toISOString(),
    escalationLevel: "ward",
    assignedWorkerId: "wrk-201",
    assignedWorkerName: "Ramesh Kumar (Junior Engineer)",
    officialNotes: "Bitumen emulsion mixture loaded on inspection van. En route to Richmond flyover.",
    procurementProjectId: "proc-101",
    priority: "high",
    wardNumber: "Ward 12",
    zoneName: "Central Zone",
    createdAt: new Date(Date.now() - 28 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 3600 * 1000).toISOString(),
    civicPointsAwarded: 25,
  },
];

export const SEED_TRANSPARENCY_SCORES: TransparencyScore[] = [
  {
    department: "Municipal Corporation",
    category: "Sanitation & Waste",
    totalGrievances: 1420,
    resolvedGrievances: 1285,
    slaAdherenceRate: 90.5,
    avgResolutionHours: 34,
    reComplaintRate: 4.8,
    transparencyIndex: 91.2,
    grade: "A+",
  },
  {
    department: "Public Works Department",
    category: "Roads & Infrastructure",
    totalGrievances: 2180,
    resolvedGrievances: 1840,
    slaAdherenceRate: 84.4,
    avgResolutionHours: 68,
    reComplaintRate: 7.2,
    transparencyIndex: 83.5,
    grade: "A",
  },
  {
    department: "Water Board / Electricity Board",
    category: "Water & Electricity",
    totalGrievances: 960,
    resolvedGrievances: 865,
    slaAdherenceRate: 90.1,
    avgResolutionHours: 18,
    reComplaintRate: 3.9,
    transparencyIndex: 92.0,
    grade: "A+",
  },
  {
    department: "Health Department",
    category: "Health Services",
    totalGrievances: 540,
    resolvedGrievances: 430,
    slaAdherenceRate: 79.6,
    avgResolutionHours: 52,
    reComplaintRate: 6.1,
    transparencyIndex: 78.4,
    grade: "B",
  },
  {
    department: "Education Department",
    category: "Education",
    totalGrievances: 390,
    resolvedGrievances: 295,
    slaAdherenceRate: 75.6,
    avgResolutionHours: 94,
    reComplaintRate: 8.5,
    transparencyIndex: 72.8,
    grade: "B",
  },
  {
    department: "Police / Traffic Department",
    category: "Law & Order / Safety",
    totalGrievances: 880,
    resolvedGrievances: 815,
    slaAdherenceRate: 92.6,
    avgResolutionHours: 14,
    reComplaintRate: 2.8,
    transparencyIndex: 94.6,
    grade: "A+",
  },
  {
    department: "Revenue Department",
    category: "Land, Revenue & Certificates",
    totalGrievances: 1640,
    resolvedGrievances: 1110,
    slaAdherenceRate: 67.7,
    avgResolutionHours: 148,
    reComplaintRate: 14.2,
    transparencyIndex: 61.5,
    grade: "C",
  },
  {
    department: "Social Welfare Department",
    category: "Welfare & Social Security",
    totalGrievances: 720,
    resolvedGrievances: 490,
    slaAdherenceRate: 68.1,
    avgResolutionHours: 136,
    reComplaintRate: 12.0,
    transparencyIndex: 63.8,
    grade: "C",
  },
  {
    department: "Pollution Control Board / Disaster Management",
    category: "Environment & Disaster",
    totalGrievances: 410,
    resolvedGrievances: 345,
    slaAdherenceRate: 84.1,
    avgResolutionHours: 38,
    reComplaintRate: 5.5,
    transparencyIndex: 85.0,
    grade: "A",
  },
  {
    department: "Anti-Corruption Bureau",
    category: "Corruption & Accountability",
    totalGrievances: 195,
    resolvedGrievances: 142,
    slaAdherenceRate: 72.8,
    avgResolutionHours: 280,
    reComplaintRate: 3.1,
    transparencyIndex: 79.5,
    grade: "B",
  },
];
